### ISSUE TITLE
Image Build fails on Step 5/7

### ISSUE THREAD

**Issue by andresvettori** [RobertoPrevato/AzureDevOps-agents#20] opened 2021-04-28 00:32 UTC
=> ERROR [5/7] RUN /scripts/base/preparemetadata.sh &&     /scripts/installers/basic.sh &&     /scripts/base/repo  0.6s
------
 > [5/7] RUN /scripts/base/preparemetadata.sh &&     /scripts/installers/basic.sh &&     /scripts/base/repos.sh &&     /scripts/helpers/apt.sh &&     /scripts/installers/7-zip.sh &&     /scripts/installers/azcopy.sh &&     /scripts/installers/gcc.sh &&     /scripts/installers/clang.sh &&     /scripts/installers/cmake.sh &&     /scripts/installers/build-essential.sh &&     /scripts/installers/azure-cli.sh &&     /scripts/installers/azure-devops-cli.sh:
#9 0.605 /bin/sh: 1: /scripts/base/preparemetadata.sh: not found
------
executor failed running [/bin/sh -c /scripts/base/preparemetadata.sh &&     /scripts/installers/basic.sh &&     /scripts/base/repos.sh &&     /scripts/helpers/apt.sh &&     /scripts/installers/7-zip.sh &&     /scripts/installers/azcopy.sh &&     /scripts/installers/gcc.sh &&     /scripts/installers/clang.sh &&     /scripts/installers/cmake.sh &&     /scripts/installers/build-essential.sh &&     /scripts/installers/azure-cli.sh &&     /scripts/installers/azure-devops-cli.sh]: exit code: 127

**Comment by RobertoPrevato** [comment] 2021-05-05 16:44
Hi @andresvettori
Sorry for not replying earlier. I have a scheduled build that runs every Saturday, it never failed in the last weeks.
You can see the GitHub Workflow runs here: https://github.com/RobertoPrevato/AzureDevOps-agents/actions

Do you have any local change in your environment?

**Comment by RobertoPrevato** [comment] 2021-05-15 07:29
Closing this issue since GitHub workflows demonstrate the build works.

**Closed as completed by RobertoPrevato** 2021-05-15 07:29 UTC

**Comment by Jedmeyer** [comment] 2021-06-17 21:51
I'm also running into this issue on WSL2 on windows 10. What's your build environment? I'd love to get some of these containers spun up on my ADO instance.

**Comment by Jedmeyer** [comment] 2021-06-17 22:43
Aha - found the cause on this one. CRLF endings are screwing with the docker daemon. If you build on windows make sure to use LF endings on the shell files.

**Comment by RobertoPrevato** [comment] 2021-06-18 08:38
Hi @Jedmeyer, thank you for the information! I was puzzled about why some users were reporting failing builds, when they always succeeded in my Azure DevOps pipelines and GitHub actions (they both run on Ubuntu).

Honestly I started using Docker when the CLI was still implemented in Python and not in Go, so a long time before it was available on Windows, and I still always use it on Ubuntu, so I never tried to build them on WSL (although I use it, too, for other purposes).

**Comment by Jedmeyer** [comment] 2021-06-18 16:08
Happy to help! I'm actually running into build issues in other spots too on WSL, so I'm going to pivot to an ubuntu build. Hopefully that knocks out everything 😊
